name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build --if-present

    - name: Deploy to Green Environment
      run: |
        # Replace with your deployment script or command for the green environment
        ./deploy-to-green.sh

    - name: Switch Traffic to Green Environment
      run: |
        # Replace with your command to switch traffic (e.g., update load balancer)
        ./switch-traffic.sh

    - name: Clean up Blue Environment
      run: |
        # Optionally, clean up the blue environment if needed
        ./clean-up-blue.sh
